### PR TITLE
Add example for using default env vars as docker build arg

### PR DESCRIPTION
**Pull request by markphelps**
Adding example on how customers can use default env vars as build arguments

### CODE REVIEW

**Comment by markphelps** [comment]
Will do

**Comment by markphelps** [comment]
Actually thats not gonna work when run locally because CommitID is only populated in CI.

**Comment by mlocher** [comment]
Very valid point though having those available locally as well would be great (though a completely different topic).

**Comment by markphelps** [comment]
Thats not really possible without depending on `git` or `mercural` to be
installed on the users machine as `jet` has no view of the commits
associated with a project. In production it gets sent that information by
the SCM

**Comment by rheinwein** [comment]
@mlocher If a user wants to simulate having the commit ID available, they can populate it manually via `--ci-commit-id`

**Comment by markphelps** [comment]
True, but just running `jet steps` in the base of this project will not work as most users/we do since there will be no commit ID

**Comment by markphelps** [comment]
We could update it to depend on the `CI` env var instead and do something like:

```
if CI {
echo "I'm running in CI environment
} else {
echo I'm running locally"
}
```

or something to that effect

**Pull request merged**
